name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - run: docker build -t yuli12345/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true yuli12345/react-test npm test

      - run: docker build -t yuli12345/multi-client ./client
      - run: docker build -t yuli12345/multi-nginx ./nginx
      - run: docker build -t yuli12345/multi-server ./server
      - run: docker build -t yuli12345/multi-worker ./worker

      - run: docker push yuli12345/multi-client
      - run: docker push yuli12345/multi-nginx
      - run: docker push yuli12345/multi-server
      - run: docker push yuli12345/multi-worker
